### PR TITLE
Fix URL Given in the Help Menu.

### LINKED ISSUE #98: Fix URL Given in the Help Menu
The tool currently gives an incorrect URL when a person runs the tool. This should be fixed so that it correctly displays the URL for the current repository. Additionally, we need to update the README.md file so that it displays the correct output.

### PR DESCRIPTION
**Pull request by duarte2025**
Fix #98 .
URL on README.md was wrong, now it directs you to the right domain

### CODE REVIEW

**Comment by duarte2025** [comment]
Correcting issue #98 .
URL on README.md was wrong, now it directs you to the right domain

**Comment by Michionlion** [comment]
@duarte2025, that comment needs to be added to the PR description by editing the first part.

**Comment by gkapfham** [comment]
Hi @duarte2025 please note that this branch is now out-of-date with the base branch. There are a significant number of changes under review in other PRs, so I encourage you to merge the latest changes from master and then check to see if your approach is still working correctly. Thanks! Finally, please note @Michionlion's suggestion that you update the description of the PR so that we can clearly see how your PR will change the master branch.

**Comment by Michionlion** [comment]
@duarte2025 What is the status of this PR? It should be straightforward to update this PR with the latest changes from `master`. After that is done this can easily be merged!

**Comment by shafferz** [comment]
This pull request was deprecated by PR #187. In the future, contributing should be easier with the addition of a `CONTRIBUTING.md` document, which is soon to come provided the merge of PR #175.

**Pull request closed without merging**
