### PR TITLE
Increase Code Coverage For display.py

### PR DESCRIPTION
**Pull request by Lancasterwu**
# Description of Pull Request

This Pull Request changes `display_welcome_message()` in `display.py` and adds a test function `test_display_student_groups` to test it.
The original function of  `display_welcome_message()` does not return a specific data type, so by Python default, it returns `None Type`, which is really hard for developers to write a test function for it. 
With the change, the test function `test_display_student_groups` tests if the welcome message provide the expected output.

With this PR, the test coverage will become 100% in `display.py` from 82%.

Fixes Part of #137  which @GatorEducator/team-lancaster and @GatorEducator/team-spencer are currently working on.

## Type of change

Please describe the pull request as one of the following: 

- [ ] Bug fix
- [ ] Breaking change
- [x] New feature
- [ ] Documentation update
- [x] Other (Increase the Test Coverage)

## Tags
This Pull Request is made by @Lancasterwu. You can also contact other members from @GatorEducator/team-lancaster and @GatorEducator/team-spencer to know more details.

### CODE REVIEW

**Comment by Michionlion** [comment]
This PR should probably be merged to `develop`, because the restructure will change a lot. That branch needs to be merged ASAP.

**Comment by Lancasterwu** [comment]
Hi @Michionlion, is there any way I can change the branch which this will merge into? I can also just wait after the develop is merged into the master branch since this is not the priority PR.

**Comment by Michionlion** [comment]
@Lancasterwu not that I know of. It may be best to just wait on this one.

**Comment by Lancasterwu** [comment]
I'm going to close this because the structure of the main repo has changed

**Pull request closed without merging**
