### PR TITLE
Django views & forms for uploading student preferences CSV

### PR DESCRIPTION
**Pull request by aubreypc**
# Description of Pull Request

This PR expands on the Django MVP:
- Allows the user to optionally upload a student preferences CSV in addition to student data CSV
- Transforms preferences CSV data into `Dict[student_name_str][Set[preferred_student_names]]` format needed in `group_graph_partition`
- Modifies upload form to only allow `numgrp` sizes accepted by `group_graph_partition`
- Adds fields to upload form for `preferences_weight` and `preferences_weight_match` and passes these into `group_graph_partition`

## Type of Change

Please describe the pull request as one of the following: 

- [ ] Bug fix
- [ ] Breaking change
- [x] New feature
- [x] Documentation update
- [ ] Other 

## Tags
@aubreypc

### CODE REVIEW

**Comment by Michionlion** [comment]
@aubreypc this can be merged if the conflicts are taken care of!

**Comment by huangs1** [comment]
@Michionlion All the conflicts have been handled and I believe that this PR is ready to be merged

**Comment by aubreypc** [comment]
Conflicts are resolved. Added a feature to use CSV uploading to create a group when the user is not logged in.

**Comment by aubreypc** [comment]
@Michionlion This is ready to merge!

**Pull request merged**
