### PR TITLE
Web/templates

### LINKED ISSUE #135: Install a CSS Framework as a Starting Point for Front-end Design
Since we are moving ahead with #94, we should begin working on the front-end design of our web application so that we can continually iterate on it in order to address usability concerns. In order to move quickly, we should use a CSS framework as a starting point in order to allow us to focus on the layout, interface, and more general principles of design. I would suggest using [Bootstrap](https://getbootstrap.com/) or [Foundation](https://foundation.zurb.com/).

It may also be a good idea to find some Bootstrap/Foundation page templates to modify instead of starting from scratch on the layout -- at least, when it comes to the more "static" features like the home page, login, etc.

Also, it will be helpful to reference #96 -- the framework will go in the static/ directory.

### PR DESCRIPTION
**Pull request by chenc-allegheny**
# Description of Pull Request

1. stored local bootstrap CSS and JS in gatorgrouper/static
2. rendered templates
3. GitHub/google authentication with login buttons on the home page

Fixes #135 

## Type of Change

Please describe the pull request as one of the following: 

- [ ] Bug fix
- [ ] Breaking change
- [x] New feature
- [ ] Documentation update
- [ ] Other (Please specify any helpful information below)

## Tags

Please tag those who are responsible for reviewing proposed changes below.
@aubreypc @Lancasterwu @Michionlion @ilikerustoo

### CODE REVIEW

**Comment by Michionlion** [comment]
This should probably be merged into `web/bootstrap` first, right @aubreypc @enpuyou @ElisiaW?

**Comment by chenc-allegheny** [comment]
I added favicon and if statements (in another branch) today so that our nav bar in base.html would display different items according to the user's authentication status, but I guess I should make another pull request after this one is approved?

**Comment by barrezuetai** [comment]
Can we merge this into master so that the views.py can be done?

**Comment by sutterj** [comment]
Is secret_key.py supposed to be committed here?  The comment in the file says not to add it to version control.

**Comment by sutterj** [comment]
@chenc-allegheny @aubreypc @enpuyou @ElisiaW 
The secret_key.py file has been committed and I do not believe that it should be.

**Comment by chenc-allegheny** [comment]
I am trying to do this using the web browser ,cuz I don't have git on my computer and I think I accidentally made changes to another branch(?)(someone please reverse whatever I did, I am sorry) I can't do this on my computer, and I can't go to school today. I will fix these stuff tomorrow.

**Comment by ursowilliam** [comment]
We have to wait until the linting errors, not associated with the web design teams code, to pass before ours will pass the code. As the errors are not in the web design code

**Comment by huangs1** [comment]
@chenc-allegheny Lines 24-59 and Lines 72-104 are identical functions. Is there a reason why this is necessary? If it is necessary,  could you please rename it so it doesn't cause an error.

**Comment by chenc-allegheny** [comment]
@huangs1  I deleted the duplicated lines, I don't know why they are there but it's fixed. :smiley:

**Comment by ElisiaW** [comment]
The merge conflicts in the pipfile.lock have been fixed!

**Comment by chenc-allegheny** [comment]
> You've committed merge conflict markers! You need to resolve the conflict and make sure to save and commit your resolutions.

You are still on our reviewer list

@Michionlion  We fixed it we fixed it ~~~~~~~~~~~~ :smiley: :smiley:  :smiley:

**Pull request closed without merging**
